### ISSUE TITLE
Error: unauthorized_client : Invalid scope for client

### ISSUE THREAD

**Issue by tolland** [XeroAPI/xero-python-oauth2-app#14]
I get 

```
Error code: 500
Error: unauthorized_client : Invalid scope for client
```

after running the app, it seems to be due to having "paymentservices" in the scope here:
https://github.com/XeroAPI/xero-python-oauth2-app/blob/f65186405f86dc838f92ac66f20371d400cd5517/app.py#L65

**Comment by RettBehrens** [comment]
You're right, paymentservices is a restricted scope. I've removed so it's not included by default. Thanks for catching!
